### ISSUE TITLE
Bot validates UPSTREAM patch with reference to maintainer repo

### ISSUE THREAD

**Issue by Gnurou** [atseanpaul/review-o-matic#9] opened 2019-06-28 04:28 UTC
Example of validated patch:

https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1644481/2

Despite being an UPSTREAM CL, the cherry-picked line is as follows:

    (cherry picked from commit c27bb30e7b6d385c5bff26406089377d678f1a1d
     git://linuxtv.org/media_tree.git)

The reference does exist in Linus' tree, so ultimately this is not a big issue, but we probably don't need the reference to the maintainer tree in that case. Maybe the bot should reject such patches?

**Comment by atseanpaul** [comment] 2019-08-02 15:40
Duplicate of #3, which was just fixed.

**Closed by atseanpaul** 2019-08-02 15:40 UTC
